version: 2
updates:
  - package-ecosystem: github-actions
    cooldown:
      default-days: 21
    directory: /
    schedule:
      interval: daily
    target-branch: main

  - package-ecosystem: gomod
    cooldown:
      default-days: 21
    directory: /
    schedule:
      interval: daily
    target-branch: main
