# https://docs.coderabbit.ai/reference/configuration

chat:
  auto_reply: true
early_access: true
issue_enrichment:
  auto_enrich:
    enabled: false
language: en-US
reviews:
  assess_linked_issues: true
  auto_apply_labels: true
  auto_review:
    base-branches:
      - dev
      - feature/*
    drafts: true
    enabled: true
  collapse_walkthrough: false
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  labeling_instructions: []
  poem: false
  profile: chill
  request_changes_workflow: true
  review_status: true
  sequence_diagrams: false
