linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive
    - unconvert
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-dirs:
    - bin
  exclude-files:
    - ".*\\.pb\\.go$"
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m

version: "2"
