// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Chunk struct {
	ID          int64
	FileID      int64
	ChunkIndex  int64
	ChunkSize   int64
	ChunkHash   string
	IsAvailable int64
}

type File struct {
	ID           int64
	Name         string
	Size         int64
	MaxChunkSize int64
	TotalChunks  int64
	Hash         string
	CreatedAt    int64
}

type Peer struct {
	ID        int64
	IpAddress string
	Port      string
}

type Swarm struct {
	ID     int64
	PeerID int64
	FileID int64
}
